[falsepositive.1]
line = 5
message = "Sigle. Il est recommandé d’ôter les points pour les sigles. (S’il s’agit d’un prénom et d’un nom, mettez un espace.)"
col_start = 9
col_end = 13
explication = "nom du jeu"

[falsepositive.2]
line = 8
message = "Sigle. Il est recommandé d’ôter les points pour les sigles. (S’il s’agit d’un prénom et d’un nom, mettez un espace.)"
col_start = 4
col_end = 8
explication = "nom du jeu"

[falsepositive.3]
line = 5
message = "Tiret d’incise : un tiret demi-cadratin [1] ou cadratin [2] est requis. (Ou éventuellement le signe “moins” [3], s’il s’agit d’une soustraction.)"
col_start = 13
col_end = 16
explication = "titre"

[falsepositive.4]
line = 5
message = "Tiret d’incise : un tiret demi-cadratin [1] ou cadratin [2] est requis. (Ou éventuellement le signe “moins” [3], s’il s’agit d’une soustraction.)"
col_start = 33
col_end = 36
explication = "titre"

[falsepositive.5]
line = 8
message = "Tiret d’incise : un tiret demi-cadratin [1] ou cadratin [2] est requis. (Ou éventuellement le signe “moins” [3], s’il s’agit d’une soustraction.)"
col_start = 8
col_end = 11
explication = "titre"
