[falsepositive.1]
line = 29
message = "Mot inconnu : systemdefaults"
col_start = 74
col_end = 88
explication = "explication d'un fichier de config"

[falsepositive.2]
line = 29
message = "Mot inconnu : DefaultSaveFormat"
col_start = 91
col_end = 108
explication = "config"

[falsepositive.3]
line = 29
message = "Guillemets typographiques fermants."
col_start = 114
col_end = 115
explication = "config"
