[falsepositive.1]
line = 25
message = "Mot inconnu : fullscreen"
col_start = 10
col_end = 20
explication = "config"

[falsepositive.2]
line = 26
message = "Mot inconnu : doublebuf"
col_start = 10
col_end = 19
explication = "config"

[falsepositive.3]
line = 26
message = "Mot inconnu : buffering"
col_start = 41
col_end = 50
explication = "config"

[falsepositive.4]
line = 28
message = "Mot inconnu : nosound"
col_start = 10
col_end = 17
explication = "config"

[falsepositive.5]
line = 29
message = "Mot inconnu : scale"
col_start = 10
col_end = 15
explication = "config"

[falsepositive.6]
line = 30
message = "Mot inconnu : gl"
col_start = 10
col_end = 12
explication = "config"

[falsepositive.7]
line = 30
message = "Mot inconnu : antialias"
col_start = 14
col_end = 23
explication = "config"

[falsepositive.8]
line = 30
message = "Mot inconnu : anti-aliasing"
col_start = 36
col_end = 49
explication = "config"
