[falsepositive.1]
line = 30
message = "L’espace se place après le point, et non avant (ou bien sert de liant entre deux lettres)."
col_start = 29
col_end = 31
explication = "extension de fichier"

[falsepositive.2]
line = 30
message = "Mettez des guillemets fermants plutôt qu’ouvrants."
col_start = 27
col_end = 29
explication = "grammalect se plante"
