[falsepositive.1]

line = 12
message = "Mot inconnu : Last"
col_start = 68
col_end = 72
explication = "Last.fm en un mot"

[falsepositive.2]

line = 12
message = "Il manque un espace."
col_start = 73
col_end = 75
explication = "Last.fm en un mot"




[falsepositive.3]

line = 12
message = "Mot inconnu : SKY"
col_start = 105
col_end = 108
explication = "SKY.fm en un mot"

[falsepositive.4]

line = 12
message = "Il manque un espace."
col_start = 109
col_end = 111
explication = "Last.fm en un mot"






[falsepositive.5]

line = 16
message = "Mot inconnu : CUE"
col_start = 16
col_end = 19
explication = "CUE sheet en un mot"

[falsepositive.6]

line = 16
message = "Mot inconnu : sheet"
col_start = 20
col_end = 25
explication = "CUE sheet en un mot"




[falsepositive.7]

line = 24
message = "Mot inconnu : Last"
col_start = 57
col_end = 61
explication = "Last.fm en un mot"

[falsepositive.8]

line = 24
message = "Il manque un espace."
col_start = 62
col_end = 64
explication = "Last.fm en un mot"



[falsepositive.9]

line = 25
message = "Il manque un espace."
col_start = 24
col_end = 27
explication = "pas de nécessité d'espace"


[falsepositive.10]

line = 56
message = "Accord de genre erroné avec « bouton »."
col_start = 36
col_end = 44
explication = "faux-positif"
