[falsepositive.1]
line = 21
message = "Mot inconnu : Object"
col_start = 229
col_end = 235
explication = "Définition de OID"

[falsepositive.2]
line = 37
message = "Mot inconnu : polling"
col_start = 58
col_end = 65
explication = "config de snmp"

[falsepositive.3]
line = 39
message = "Mot inconnu : polling"
col_start = 5
col_end = 12
explication = "explication du polling sous snmp"

[falsepositive.4]
line = 41
message = "Mot inconnu : handlers"
col_start = 728
col_end = 736
explication = "explication des traps handlers"

[falsepositive.5]
line = 46
message = "Mot inconnu : v1"
col_start = 9
col_end = 11
explication = "version de snmp 1"

[falsepositive.6]
line = 47
message = "Mot inconnu : v2c"
col_start = 9
col_end = 12
explication = "version snmp 2c"

[falsepositive.7]
line = 48
message = "Mot inconnu : v3"
col_start = 9
col_end = 11
explication = "version snmp 3"

[falsepositive.8]
line = 110
message = "Mot inconnu : MIBDIRS"
col_start = 13
col_end = 20
explication = "config"

[falsepositive.9]
line = 112
message = "Mot inconnu : SNMPDRUN"
col_start = 6
col_end = 14
explication = "config"

[falsepositive.10]
line = 114
message = "Mot inconnu : SNMPDOPTS"
col_start = 6
col_end = 15
explication = "config"

[falsepositive.11]
line = 116
message = "Mot inconnu : TRAPDRUN"
col_start = 6
col_end = 14
explication = "config"

[falsepositive.12]
line = 118
message = "Mot inconnu : TRAPDOPTS"
col_start = 6
col_end = 15
explication = "config"

[falsepositive.13]
line = 125
message = "Mot inconnu : MIBs"
col_start = 17
col_end = 21
explication = "config"

[falsepositive.14]
line = 141
message = "Mot inconnu : Net-SNMP"
col_start = 16
col_end = 24
explication = "config"

[falsepositive.15]
line = 150
message = "Mot inconnu : MIBs"
col_start = 17
col_end = 21
explication = "config"

[falsepositive.16]
line = 161
message = "Mot inconnu : snmpwalk"
col_start = 5
col_end = 13
explication = "utilitaire de snmp"

[falsepositive.17]
line = 205
message = "Mot inconnu : snmpget"
col_start = 5
col_end = 12
explication = "utilitaire de snmp"

[falsepositive.18]
line = 21
message = "Mot inconnu : Identifiers"
col_start = 236
col_end = 247
explication = "définition de OID"

[falsepositive.19]
line = 110
message = "Mot inconnu : MIBs"
col_start = 65
col_end = 69
explication = "config"

[falsepositive.23]
line = 21
message = "Mot inconnu : Identifiers"
col_start = 237
col_end = 248
explication = "définition de OID"

[falsepositive.25]
line = 114
message = "Mot inconnu : SNMPD"
col_start = 50
col_end = 55
explication = "config"

[falsepositive.26]
line = 118
message = "Mot inconnu : SNMPTRAPD"
col_start = 50
col_end = 59
explication = "config"

[falsepositive.27]
line = 125
message = "Mot inconnu : tkmib"
col_start = 27
col_end = 32
explication = "config"

[falsepositive.28]
line = 150
message = "Mot inconnu : SNMPb"
col_start = 27
col_end = 32
explication = "config"
