[falsepositive.1]
line = 8
message = "Mot inconnu : is"
col_start = 80
col_end = 82
explication = "anglais"

[falsepositive.2]
line = 8
message = "Mot inconnu : tool"
col_start = 85
col_end = 89
explication = "anglais"

[falsepositive.3]
line = 8
message = "Mot inconnu : that"
col_start = 90
col_end = 94
explication = "anglais"

[falsepositive.4]
line = 8
message = "Mot inconnu : allows"
col_start = 95
col_end = 101
explication = "anglais"

[falsepositive.5]
line = 8
message = "Mot inconnu : you"
col_start = 102
col_end = 105
explication = "anglais"

[falsepositive.6]
line = 8
message = "Mot inconnu : to"
col_start = 106
col_end = 108
explication = "anglais"

[falsepositive.7]
line = 8
message = "Mot inconnu : display"
col_start = 109
col_end = 116
explication = "anglais"

[falsepositive.8]
line = 8
message = "Mot inconnu : dialog"
col_start = 122
col_end = 128
explication = "anglais"

[falsepositive.9]
line = 8
message = "Mot inconnu : from"
col_start = 135
col_end = 139
explication = "anglais"

[falsepositive.10]
line = 8
message = "Mot inconnu : the"
col_start = 140
col_end = 143
explication = "anglais"

[falsepositive.11]
line = 8
message = "Mot inconnu : command"
col_start = 144
col_end = 151
explication = "anglais"

[falsepositive.12]
line = 8
message = "Mot inconnu : line"
col_start = 152
col_end = 156
explication = "anglais"

[falsepositive.13]
line = 8
message = "Mot inconnu : and"
col_start = 157
col_end = 160
explication = "anglais"

[falsepositive.14]
line = 8
message = "Mot inconnu : through"
col_start = 161
col_end = 168
explication = "anglais"

[falsepositive.15]
line = 8
message = "Mot inconnu : It"
col_start = 184
col_end = 186
explication = "anglais"

[falsepositive.16]
line = 8
message = "Mot inconnu : similar"
col_start = 190
col_end = 197
explication = "anglais"

[falsepositive.17]
line = 8
message = "Mot inconnu : gdialog"
col_start = 201
col_end = 208
explication = "anglais"

[falsepositive.18]
line = 8
message = "Mot inconnu : intended"
col_start = 217
col_end = 225
explication = "anglais"

[falsepositive.19]
line = 8
message = "Mot inconnu : saner"
col_start = 232
col_end = 237
explication = "anglais"

[falsepositive.20]
line = 8
message = "Mot inconnu : comes"
col_start = 242
col_end = 247
explication = "anglais"

[falsepositive.21]
line = 8
message = "Mot inconnu : family"
col_start = 262
col_end = 268
explication = "anglais"

[falsepositive.22]
line = 8
message = "Mot inconnu : Xdialog"
col_start = 280
col_end = 287
explication = "anglais"

[falsepositive.23]
line = 8
message = "Mot inconnu : cdialog"
col_start = 293
col_end = 300
explication = "anglais"

[falsepositive.24]
line = 8
message = "Mot inconnu : it"
col_start = 306
col_end = 308
explication = "anglais"

[falsepositive.25]
line = 8
message = "Mot inconnu : those"
col_start = 319
col_end = 324
explication = "anglais"

[falsepositive.26]
line = 8
message = "Mot inconnu : projects"
col_start = 325
col_end = 333
explication = "anglais"

[falsepositive.27]
line = 8
message = "Mot inconnu : by"
col_start = 334
col_end = 336
explication = "anglais"

[falsepositive.28]
line = 8
message = "Mot inconnu : having"
col_start = 337
col_end = 343
explication = "anglais"

[falsepositive.29]
line = 8
message = "Mot inconnu : cooler"
col_start = 346
col_end = 352
explication = "anglais"

[falsepositive.30]
line = 8
message = "Mot inconnu : name"
col_start = 353
col_end = 357
explication = "anglais"

[falsepositive.31]
line = 10
message = "Mot inconnu : gdialog"
col_start = 156
col_end = 163
explication = "anglais"

[falsepositive.32]
line = 10
message = "Mot inconnu : dialog"
col_start = 242
col_end = 248
explication = "anglais"

[falsepositive.33]
line = 10
message = "Mot inconnu : xdialog"
col_start = 306
col_end = 313
explication = "commande de zenity"

[falsepositive.34]
line = 10
message = "Mot inconnu : cdialog"
col_start = 321
col_end = 328
explication = "commande de zenity"

[falsepositive.35]
line = 48
message = "Mot inconnu : entry"
col_start = 61
col_end = 66
explication = "type de config"

[falsepositive.36]
line = 56
message = "Mot inconnu : span"
col_start = 96
col_end = 100
explication = "config"

[falsepositive.37]
line = 56
message = "Mot inconnu : color"
col_start = 101
col_end = 106
explication = "config"

[falsepositive.38]
line = 78
message = "Mot inconnu : span"
col_start = 82
col_end = 86
explication = "config"

[falsepositive.39]
line = 78
message = "Mot inconnu : font-family"
col_start = 87
col_end = 98
explication = "config"

[falsepositive.40]
line = 119
message = "Mot inconnu : entry"
col_start = 44
col_end = 49
explication = "config"

[falsepositive.41]
line = 130
message = "Mot inconnu : entry-text"
col_start = 53
col_end = 63
explication = "config"
